### ISSUE TITLE
Not working inside strings in Python files

### ISSUE THREAD

**Issue by SmartManoj** [varunkumar/google-input-tools#18]

**Comment by varunkumar** [comment]
@SmartManoj Which version of the extension are you using? I see that it is working fine for me.

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/226535014-c63a3220-0a65-4e07-9122-301f756488c3.png)

**Comment by varunkumar** [comment]
@SmartManoj Is the extension activated? `Ctrl + Shift + I` is the shortcut for it. It will show an indicator like this on the status bar. 
![image](https://user-images.githubusercontent.com/509433/226537787-0cb4d08d-12a2-4cff-bd21-264fc528e8c3.png)

**Comment by SmartManoj** [comment]
yes. For without quotes, sometimes works and for sometimes need to delete the last char and type again. Internet speed is 20Mbps

**Comment by SmartManoj** [comment]
https://user-images.githubusercontent.com/7231077/226540112-c3808fb6-da16-476f-8f71-8b563d883e3e.mp4

**Comment by varunkumar** [comment]
You have to press `Ctrl + space` for the suggestions to show up. Is it not showing up even after that?

**Comment by SmartManoj** [comment]
Yes, works if I press that (also update in reaadme).  But in the video, it shows without pressing for sometimes. Would be better if it is so.

**Comment by varunkumar** [comment]
Even in the demo video, I was pressing `Ctrl + space`, which is the default mapping for triggering the auto-suggestions.

**Comment by varunkumar** [comment]
@SmartManoj Good to close this issue?

**Comment by SmartManoj** [comment]
Seems there is no demo video.

**Comment by varunkumar** [comment]
I meant this one -- https://github.com/varunkumar/google-input-tools/raw/master/assets/images/demo.gif
